### PR TITLE
Add Qubes support and include information on installing dependencies in README

### PR DESCRIPTION
**Pull request by skyzzuu**
Several changes to allow kloak to work in Qubes in sys-usb if a usb keyboard/mouse is in use or dom0 if a PS/2 keyboard/mouse is in use:
- Detect if Kloak is running in Qubes, if not, kloak will follow the normal execution flow
- Stop the qubes-input-sender services associated with devices so kloak can grab them
- In the event the rescue key sequence is sent, kloak will restart the associated qubes-input-sender services

This will affect typing in all qubes, it's not currently possible to limit it to individual qubes.

Related issue: https://github.com/vmonaco/kloak/issues/47 

Unrelated to Qubes support:
- Added information into README.md on how to install the dependencies necessary to build the version in the dev branch

### CODE REVIEW

**Comment by adrelanos** [comment]
https://github.com/vmonaco/kloak/pull/49#issuecomment-1657214692

**Comment by skyzzuu** [comment]
I didn't realize the other changes I was working on would also be pulled into this pull request. The additions in the main_loop regarding EV_REL events is for providing mouse cursor movement obfuscation, close to what's described in (https://arxiv.org/pdf/2101.09087.pdf), but not exactly the same. I changed the default to 0 noise so it's off by default, it works as expected but takes some adjustment, so I'm figuring out what the best noise value would be.

It can be adjusted with the -n option, which controls the max number of pixels the cursor will move perpendicular to the original move.

**Comment by skyzzuu** [comment]
Several more features added:

Added reading config options from /etc/kloak/kloak.conf
Added the ability to specify different maximum delays for mouse movements and key events
Added several security-related compile options to the makefile
Added color to output to make it more readable

Added the ability to temporarily disable and re-enable kloak, similar to the rescue sequence, but instead of exiting kloak stops adding delay to events until the disable/re-enable key sequence is seen again. It will then go back to adding delay and/or noise to events

**Comment by skyzzuu** [comment]
I have a pull request open with qubes to address the input device creation on their side for qubes support (https://github.com/QubesOS/qubes-gui-agent-linux/pull/194). That's going to be the better route as that will allow kloak to be used in individual qubes instead of having to use it in all of them or none of them.


I'm going to close this PR, remove the sections that add qubes support, then submit the other features I added as several smaller PRs so they're easier to review.

**Comment by skyzzuu** [comment]
I have a pull request open with qubes to address the input device creation on their side for qubes support (https://github.com/QubesOS/qubes-gui-agent-linux/pull/194). That's going to be the better route as that will allow kloak to be used in individual qubes instead of having to use it in all of them or none of them.

I'm going to close this PR, remove the sections that add qubes support, then submit the other features I added as several smaller PRs so they're easier to review.

**Comment by vmonaco** [comment]
didn't get a chance yet to dig into this yet, but very interested in the motion obfuscation. and would love smaller PRs, thank you!

**Pull request closed without merging**
